### ISSUE TITLE
Flickering Search Command

### ISSUE THREAD

**Issue by bharris2205** [Apptha/Airhotels#1]
While in uat1.contus./us/services/SVEP4054/index.php/ a user enters search location in “where do you want to go?”, and clicks “search” results in “flickering” defect which prevents completion of search command

**Comment by VarunContus** [comment]
Hi Bharris,

We have fixed the Advanced search and flickering issue in the uat1.contus./us/services/SVEP4054/index.php/. Now the Advanced Search is working fine.

Thanks,
Varun P.V.
